title: "Christopher Khoury"
description: "Executive resume"
url: "https://khourycm.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional site-wide visual theme
minimal_mistakes_skin: "air"
